# Análisis de los Proyectos Mineros de Mendoza

## Etapa 1 — Exploración, transformación y visualización

**Tema:** Proyectos mineros de la provincia de Mendoza.

### Objetivo

Analizar las características y distribución de los proyectos mineros de Mendoza como base para las etapas posteriores de aprendizaje supervisado y clustering.

## Importaciones

Usaremos las librerías trabajadas en clase y `scikit-learn` para las etapas de aprendizaje supervisado y no supervisado.

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:,.4f}".format)

## Carga de datos

Los archivos originales se guardarán en `data/raw/`.

Primero veremos las columnas reales antes de definir transformaciones.

In [32]:
df= pd.read_csv(
    "../data/raw/Cartera-de-Proyectos-Mineros-Metaliferos-y-Litio-del-SIACAM(MetalIferos y litio).csv",
    encoding="cp1252", #lo adaptamos para que pueda leer la codificacion Windows-1252 (UnicodeDecodeError)
    sep=";"# los datos del csv viene separados por; lo que ocasiona ParserError
)

df.head()

,N°,NOMBRE,LATITUD,LONGITUD,MINERAL PRINCIPAL,PROVINCIA,ESTADO,CONTROLANTE (1°),PORCENTAJE (1°),ORIGEN (1°),CONTROLANTE (2°),ORIGEN (2°),PORCENTAJE (2°),CONTROLANTE (3°),PORCENTAJE (3°),ORIGEN (3°),Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,1.0000,20 de septiembre,"-24,896","-68,136",Hierro,Salta,Exploración inicial,Diego Ruben Omar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0000,Acazoque,"-24,291","-66,378",Plomo,Salta,Exploración inicial,Nuñez Ramon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0000,Acoite/Hornillos,"-22,305","-65,107",Plomo,Salta,Exploración inicial,Rubiolo Daniel Gerardo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0000,Adamo,"-41,162","-68,505",Oro,Río Negro,Prospección,Valcheta Exploraciones,100%,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0000,Aguas Amargas,"-24,685","-66,903",Cobre,Salta,Exploración inicial,Lithium S Corp. S.A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Diagnóstico inicial

Operaciones iniciales: `head()`, `info()`, `describe()`, valores faltantes, duplicados y nombres de columnas.

In [37]:
df.info() #nos muestra cant filas, col y nombres, cant val nulos

<class 'pandas.DataFrame'>
RangeIndex: 1002 entries, 0 to 1001
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   N°                 331 non-null    float64
 1   NOMBRE             331 non-null    str
 2   LATITUD            331 non-null    str
 3   LONGITUD           331 non-null    str
 4   MINERAL PRINCIPAL  331 non-null    str
 5   PROVINCIA          331 non-null    str
 6   ESTADO             331 non-null    str
 7   CONTROLANTE (1°)   236 non-null    str
 8   PORCENTAJE (1°)    210 non-null    str
 9   ORIGEN (1°)        212 non-null    str
 10  CONTROLANTE (2°)   94 non-null     str
 11  ORIGEN (2°)        91 non-null     str
 12  PORCENTAJE (2°)    94 non-null     str
 13  CONTROLANTE (3°)   92 non-null     str
 14  PORCENTAJE (3°)    89 non-null     str
 15  ORIGEN (3°)        92 non-null     str
 16  Unnamed: 16        0 non-null      float64
 17  Unnamed: 17        0 non-null      float64
 18  Unnamed: 18        0 non-null      float64
 19  Unnamed: 19        0 non-null      float64
 20  Unnamed: 20        0 non-null      float64
 21  Unnamed: 21        0 non-null      float64
 22  Unnamed: 22        0 non-null      float64
 23  Unnamed: 23        0 non-null      float64
 24  Unnamed: 24        0 non-null      float64
 25  Unnamed: 25        0 non-null      float64
dtypes: float64(11), str(15)
memory usage: 203.7 KB

In [38]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
N°,331.0000,NaN,NaN,NaN,166.0000,95.6957,1.0000,83.5000,166.0000,248.5000,331.0000
NOMBRE,331,320,Incahuasi,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LATITUD,331,320,"-41,162",2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LONGITUD,331,324,"-66,401",3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MINERAL PRINCIPAL,331,15,Cobre,77,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PROVINCIA,331,11,Salta,145,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ESTADO,331,10,Exploración inicial,131,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CONTROLANTE (1°),236,148,Southern Copper Corp.,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PORCENTAJE (1°),210,15,100%,180,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ORIGEN (1°),212,12,Canadá,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CONTROLANTE (2°),94,27,-,63,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ORIGEN (2°),91,10,-,63,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PORCENTAJE (2°),94,16,-,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CONTROLANTE (3°),92,5,-,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PORCENTAJE (3°),89,4,-,85,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ORIGEN (3°),92,3,-,89,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 16,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 17,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 18,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 19,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 20,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 21,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 22,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 23,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 24,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 25,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df.isnull().sum().sort_values(ascending=False)

Unnamed: 25          1002
Unnamed: 24          1002
Unnamed: 18          1002
Unnamed: 19          1002
Unnamed: 20          1002
Unnamed: 21          1002
Unnamed: 22          1002
Unnamed: 23          1002
Unnamed: 17          1002
Unnamed: 16          1002
PORCENTAJE (3°)       913
ORIGEN (2°)           911
ORIGEN (3°)           910
CONTROLANTE (3°)      910
CONTROLANTE (2°)      908
PORCENTAJE (2°)       908
PORCENTAJE (1°)       792
ORIGEN (1°)           790
CONTROLANTE (1°)      766
ESTADO                671
MINERAL PRINCIPAL     671
LONGITUD              671
LATITUD               671
NOMBRE                671
N°                    671
PROVINCIA             671
dtype: int64

In [42]:
df.duplicated().sum()

np.int64(670)

In [43]:
df.columns.tolist()

['N°',
 'NOMBRE',
 'LATITUD',
 'LONGITUD',
 'MINERAL PRINCIPAL',
 'PROVINCIA',
 'ESTADO',
 'CONTROLANTE (1°)',
 'PORCENTAJE (1°)',
 'ORIGEN (1°)',
 'CONTROLANTE (2°)',
 'ORIGEN (2°)',
 'PORCENTAJE (2°)',
 'CONTROLANTE (3°)',
 'PORCENTAJE (3°)',
 'ORIGEN (3°)',
 'Unnamed: 16',
 'Unnamed: 17',
 'Unnamed: 18',
 'Unnamed: 19',
 'Unnamed: 20',
 'Unnamed: 21',
 'Unnamed: 22',
 'Unnamed: 23',
 'Unnamed: 24',
 'Unnamed: 25']

In [47]:
df_mendoza=df[df["PROVINCIA"]=="Mendoza"]
df_mendoza.head()

,N°,NOMBRE,LATITUD,LONGITUD,MINERAL PRINCIPAL,PROVINCIA,ESTADO,CONTROLANTE (1°),PORCENTAJE (1°),ORIGEN (1°),CONTROLANTE (2°),ORIGEN (2°),PORCENTAJE (2°),CONTROLANTE (3°),PORCENTAJE (3°),ORIGEN (3°),Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
56,57.0000,Cerro Amarillo,"-35,27361","-70,15611",Cobre,Mendoza,Exploración inicial,Wincul S.A.,100%,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,79.0000,Corcovo,"-35,5","-69,75",Uranio,Mendoza,Exploración inicial,Blue Sky Uranium Corp.,100%,Canadá,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,90.0000,Don Sixto,"-36,29308","-68,45586",Oro,Mendoza,Exploración avanzada,Pan American Silver Corp,100%,Canadá,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,135.0000,Hierro Indio,-35,"-69,783333",Hierro,Mendoza,Exploración avanzada,Orvana Minerals Corp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,143.0000,Huemules,"-36,1539145","-69,2049679",Uranio,Mendoza,Exploración inicial,Jaguar Uranium Corp.,100%,Canadá,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
df_mendoza = df[df['PROVINCIA'].fillna('').str.contains('mendoza', case=False)]# filtramos filas que contengan "mendoza" como "PROVINCIA" (case-insensitive)
df_mendoza# mostramos todas las filas encontradas sin truncar

,N°,NOMBRE,LATITUD,LONGITUD,MINERAL PRINCIPAL,PROVINCIA,ESTADO,CONTROLANTE (1°),PORCENTAJE (1°),ORIGEN (1°),CONTROLANTE (2°),ORIGEN (2°),PORCENTAJE (2°),CONTROLANTE (3°),PORCENTAJE (3°),ORIGEN (3°),Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
56,57.0000,Cerro Amarillo,"-35,27361","-70,15611",Cobre,Mendoza,Exploración inicial,Wincul S.A.,100%,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,79.0000,Corcovo,"-35,5","-69,75",Uranio,Mendoza,Exploración inicial,Blue Sky Uranium Corp.,100%,Canadá,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,90.0000,Don Sixto,"-36,29308","-68,45586",Oro,Mendoza,Exploración avanzada,Pan American Silver Corp,100%,Canadá,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,135.0000,Hierro Indio,-35,"-69,783333",Hierro,Mendoza,Exploración avanzada,Orvana Minerals Corp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,143.0000,Huemules,"-36,1539145","-69,2049679",Uranio,Mendoza,Exploración inicial,Jaguar Uranium Corp.,100%,Canadá,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,278.0000,San Jorge (PSJ Cobre Mendocino),"-32,2448","-69,43887",Cobre,Mendoza,Prefactibilidad,Zonda Metals GmBH,90%,Suiza,Grupo Alberdi,Argentina,10%,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,292.0000,Sierra Pintada,"-34,9563","-68,6119",Uranio,Mendoza,Factibilidad,CNEA,100%,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN